---
title: "CDC-data-analysis"
author: "Justin Rivera"
date: "2023-09-30"
output: pdf_document
---

```{r, message = FALSE}
library(tidyverse)
library(knitr)
```


```{r}
cdc <- read.csv('CDC-spotify.csv')
```


```{r}

cdc1 = cdc |> 
  rename('Available Markets' = Available.Markets, 'Duration (sec)' = Duration..sec., 'Track Name' = Track.Name)
```

```{r}
spotify_data = cdc1 |> 
  select(-X)
```


```{r}
average_years = spotify_data |> 
  group_by(Year) |> 
  summarize(average_popularity = mean(Popularity))
  
average_years
```
```{r}
average_years |> 
  ggplot(mapping = aes(x= Year, y = average_popularity)) +
  geom_point(color = "#800000") +
  geom_smooth(method = "lm", color = '#FF69B4', na.rm = TRUE)
```
```{r}
spotify_data |> 
  ggplot(mapping = aes(x = Explicit)) + 
  geom_bar(aes(color = "#FF69B4", fill = Explicit)) + 
  scale_color_manual(values = c("#FF69B4", "#800000")) +
  labs(title = "Number of Explicit vs. Non-explicit songs")


```


```{r}
average_explicit = spotify_data |> 
  group_by(Explicit) |> 
  summarize(Explicit_Popularity = mean(Popularity))
kable(average_explicit)

```

```{r}
spotify_data |> 
  filter(`Duration (sec)` < 3000) |> 
  ggplot(mapping = aes(x = `Duration (sec)`, y = Popularity)) +
  geom_point(aes(color = Explicit)) +
   scale_color_manual(values = c("#FF69B4", "#800000")) +
  geom_smooth(method = 'lm', color = "#ADD8E6", se = FALSE) +
    labs(title = "Relationship Between Song Popularity and Duration", 
       x="Song Duration (in seconds)", 
      y="Song Popularity",  
       caption = "Source: Spotify API ")

```



```{r}
total_mean_duration = mean(spotify_data$`Duration (sec)`)
average_artists = spotify_data |> 
  group_by(Artist) |> 
  summarize(`Total Popularity` = sum(Popularity),  
            Count = n(), 
            `Average Duration` = mean(`Duration (sec)`) ) |> 
  arrange(desc(`Total Popularity`))
```


```{r, fig.width = 15}
average_artists |> 
  filter(`Total Popularity` > 1146) |> 
  ggplot(mappping = aes(x = Artist, y = `Total Popularity`)) + 
  geom_col(aes(x = Artist, y = `Total Popularity`, fill = Artist)) + 
  labs(title = "Total Popularity of top ten artists")
```

```{r}
average_artists |> 
  filter(`Total Popularity` > 1146) |> 
  ggplot(mappping = aes(x = Artist, y = `Average Duration`)) + 
  geom_col(aes(x = Artist, y = `Average Duration`, fill = Artist)) + 
  labs(title = "Average Duration of top ten artists")
```

```{r}


Explicit_ratio = spotify_data |> 
  group_by(Year) |> 
  summarize(`Explicit Ratio` = sum(Explicit == "True")/n())

kable(Explicit_ratio)
```

```{r}
Explicit_ratio |> 
  ggplot(mapping = aes(x = as.factor(Year), y = `Explicit Ratio`)) +
  geom_point()
```

```{r}
popularity_model = lm(Popularity~Year + `Available Markets` + `Duration (sec)` + as.factor(Explicit), data = spotify_data)

summary(popularity_model)
plot(Popularity~Year + `Available Markets` + `Duration (sec)` + as.factor(Explicit), data = spotify_data)
```
```{r}
summary(popularity_model)
```